### ISSUE TITLE
"todo.tags.backgroundColors" has been renamed to "todo.colors.tags.background"

### ISSUE THREAD

**Issue by Orphu7** [fabiospampinato/vscode-todo-plus#146]
Starting today I get this message as an error:
"todo.tags.backgroundColors" has been renamed to "todo.colors.tags.background"
![image](https://user-images.githubusercontent.com/16332978/48332740-37f1c400-e655-11e8-965c-ad94cfb375fe.png)

Todo+ version 4.10.0
VSCode version: 1.28.2

I tried reinstalling the extension, but that didn't change anything.
This is what is shown in the developer tools:

`extension Host] Activating extension 'fabiospampinato.vscode-todo-plus' failed: Invalid configuration, check the changelog.
t.log @ /C:/Users/me/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:282
/C:/Users/me/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:282 [Extension Host] Activating extension `fabiospampinato.vscode-todo-plus` failed:  Invalid configuration, check the changelog
t.log @ /C:/Users/me/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:282
/C:/Users/me/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:282 [Extension Host] Here is the error stack:  Error: Invalid configuration, check the changelog
	at Object.check (C:\Users\me\.vscode\extensions\fabiospampinato.vscode-todo-plus-4.10.0\out\extension.js:9:72124)
	at t.activate (C:\Users\me\.vscode\extensions\fabiospampinato.vscode-todo-plus-4.10.0\out\extension.js:648:62963)
	at Function.t._callActivateOptional (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:626:411)
	at Function.t._callActivate (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:626:90)
	at c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:625:263
	at Object.g [as _notify] (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:78:971)
	at Object.enter (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:277)
	at n.Class.derive._oncancel._run (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:84:100)
	at n.Class.derive._oncancel._completed (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:83:559)
	at c (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:86:1011)
	at $.then.o.(anonymous function) (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:87:205)
	at Object.g [as _notify] (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:78:971)
	at Object.enter (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:277)
	at n.Class.derive._oncancel._run (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:84:100)
	at n.Class.derive._oncancel._completed (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:83:559)
	at c (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:86:1011)
	at $.then.o.(anonymous function) (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:87:205)
	at Object.g [as _notify] (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:78:971)
	at Object.enter (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:277)
	at n.Class.derive._oncancel._run (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:84:100)
	at n.Class.derive._oncancel._completed (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:83:559)
	at e.resolveOk (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:444:313)
	at t._receiveReply (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:640:117)
	at t._receiveOneMessage (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:638:425)
	at c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:926
	at c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:138
	at e.fire (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at a (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:213)
	at Socket._socketDataListener (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:432)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
/C:/Users/me/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2374 Todo+: "todo.tags.backgroundColors" has been renamed to "todo.colors.tags.background"
t.onDidNotificationChange @ /C:/Users/me/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2374
/C:/Users/me/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3294 Activating extension 'fabiospampinato.vscode-todo-plus' failed: Invalid configuration, check the changelog.
E._logMessageInConsole @ /C:/Users/me/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3294
/C:/Users/me/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:282 [Extension Host] ApplicationInsights:CorrelationIdManager Array(1)
t.log @ /C:/Users/me/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:282
C:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-window.js:5 [uncaught exception]: TypeError: Cannot read property 'isWrapped' of undefined
onUnexpectedError @ C:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-window.js:5
C:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-window.js:5 TypeError: Cannot read property 'isWrapped' of undefined
    at Buffer.getWrappedRangeForLine (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-xterm\lib\Buffer.js:205:50)
    at BufferStringIterator.next (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-xterm\lib\Buffer.js:305:34)
    at Linkifier._linkifyRows (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-xterm\lib\Linkifier.js:65:37)
    at c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-xterm\lib\Linkifier.js:53:69`

**Comment by samael205** [comment]
only rename in you config files "todo.tags.backgroundColors" to "todo.colors.tags.background" and "todo.tags.foregroundColors" to "todo.colors.tags.foreground"

**Comment by Orphu7** [comment]
That was it, thanks!

**Comment by sergiomoura** [comment]
> only rename in you config files "todo.tags.backgroundColors" to "todo.colors.tags.background" and "todo.tags.foregroundColors" to "todo.colors.tags.foreground"

How can i do this?

**Comment by samael205** [comment]
find your config file
